---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: valheim

namePrefix: valheim-game-

commonLabels:
  game: Valheim
  app: valheim-game-server

resources:
  - namespace.yaml
  - service.yaml
  - persistentvolumeclaims.yaml
  - statefulset.yaml

images:
  - name: game-server
    newName: ghcr.io/lloesche/valheim-server
    newTag: latest

secretGenerator:
  - name: server-password
    files:
      - secret/password.txt
    type: Opaque

configMapGenerator:
  - name: server-envs
    env: configmap/server.env
