apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
  - name: game1
    port: 2456
    targetPort: game1
    nodePort: 32456
    protocol: UDP
  - name: game2
    port: 2457
    targetPort: game2
    nodePort: 32457
    protocol: UDP
  - name: game3
    port: 2458
    targetPort: game3
    nodePort: 32458
    protocol: UDP
  selector:
    app: valheim-game-server
    game: Valheim
