on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'kustomize'
        iac_version: 'v3'
        policy_type: 'k8s'
        only_warn: true
        verbose: true
        iac_dir: deploy
